name: Tests Only

on:
    push:
      branches-ignore:
        - main
        - master

jobs:
  run-all-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.3

      - name: All the Tests and Coverage Checks
        run: mvn clean install